--- MINISTERS

insert into minister(first_name, last_name) values ('Philip', 'Alajoki')
insert into minister(first_name, last_name) values ('David', 'Anderson')
insert into minister(first_name, last_name) values ('David', 'Anderson')
insert into minister(first_name, last_name) values ('Todd', 'Anderson')
insert into minister(first_name, last_name) values ('Jon', 'Bloomquist')
insert into minister(first_name, last_name) values ('David', 'Edwards')
insert into minister(first_name, last_name) values ('Andrew', 'Forstie')
insert into minister(first_name, last_name) values ('James', 'Frantti')
insert into minister(first_name, last_name) values ('Randall', 'Haapala')
insert into minister(first_name, last_name) values ('Robert', 'Haapala')
insert into minister(first_name, last_name) values ('Paul', 'Haataja')
insert into minister(first_name, last_name) values ('Steven', 'Haataja')
insert into minister(first_name, last_name) values ('Jouko', 'Haapsaari')
insert into minister(first_name, last_name) values ('Arthur', 'Harju')
insert into minister(first_name, last_name) values ('Randall', 'Herrala')
insert into minister(first_name, last_name) values ('Randy', 'Hillukka')
insert into minister(first_name, last_name) values ('Jeremy', 'Honga')
insert into minister(first_name, last_name) values ('Ronald', 'Honga')
insert into minister(first_name, last_name) values ('Paul', 'Honkala')
insert into minister(first_name, last_name) values ('Andrew', 'Hotari')
insert into minister(first_name, last_name) values ('Mauri', 'Hotari')
insert into minister(first_name, last_name) values ('Petri', 'Hotari')
insert into minister(first_name, last_name) values ('Thomas', 'Huhta')
insert into minister(first_name, last_name) values ('Phillip', 'Huhta')
insert into minister(first_name, last_name) values ('Hannu', 'Janhunen')
insert into minister(first_name, last_name) values ('Brian', 'Johnson')
insert into minister(first_name, last_name) values ('Dale', 'Johnson')
insert into minister(first_name, last_name) values ('Daniel', 'Jurmu')
insert into minister(first_name, last_name) values ('Eric', 'Jurmu')
insert into minister(first_name, last_name) values ('James', 'Jurmu')
insert into minister(first_name, last_name) values ('Steven', 'Kallinen')
insert into minister(first_name, last_name) values ('Melvin', 'Kallio')
insert into minister(first_name, last_name) values ('Wayne', 'Kallio')
insert into minister(first_name, last_name) values ('James', 'Keplinger')
insert into minister(first_name, last_name) values ('Tommi', 'Kinnunen')
insert into minister(first_name, last_name) values ('George', 'Koivukangas')
insert into minister(first_name, last_name) values ('Craig', 'Kumpula')
insert into minister(first_name, last_name) values ('Eugene', 'Kumpula')
insert into minister(first_name, last_name) values ('Michael', 'Kumpula')
insert into minister(first_name, last_name) values ('Reino', 'Kuoppala')
insert into minister(first_name, last_name) values ('Michael', 'Kuopus')
insert into minister(first_name, last_name) values ('Peter', 'Kuopus')
insert into minister(first_name, last_name) values ('Donald', 'Lahti')
insert into minister(first_name, last_name) values ('Steven', 'Laiho')
insert into minister(first_name, last_name) values ('Darwin', 'Lake')
insert into minister(first_name, last_name) values ('Walter', 'Lampi')
insert into minister(first_name, last_name) values ('Mark', 'Lee')
insert into minister(first_name, last_name) values ('John', 'Lehtola')
insert into minister(first_name, last_name) values ('Joseph', 'Lehtola')
insert into minister(first_name, last_name) values ('Peter', 'Lever')
insert into minister(first_name, last_name) values ('Markus', 'Lohi')
insert into minister(first_name, last_name) values ('Blaine', 'Maki')
insert into minister(first_name, last_name) values ('Eric', 'Mattila')
insert into minister(first_name, last_name) values ('James', 'Moll')
insert into minister(first_name, last_name) values ('Keith', 'Moll')
insert into minister(first_name, last_name) values ('Nathan', 'Muhonen')
insert into minister(first_name, last_name) values ('Lauri', 'Nevala')
insert into minister(first_name, last_name) values ('Paul', 'Nevala')
insert into minister(first_name, last_name) values ('Richard', 'Nevala')
insert into minister(first_name, last_name) values ('David', 'Niemi')
insert into minister(first_name, last_name) values ('Rodney', 'Nikula')
insert into minister(first_name, last_name) values ('Timothy', 'Niskanen')
insert into minister(first_name, last_name) values ('David', 'Ojala')
insert into minister(first_name, last_name) values ('Matthew', 'Ojala')
insert into minister(first_name, last_name) values ('Joseph', 'Ojalehto')
insert into minister(first_name, last_name) values ('Karl', 'Ojalehto')
insert into minister(first_name, last_name) values ('Daniel', 'Parks')
insert into minister(first_name, last_name) values ('Howard', 'Parks')
insert into minister(first_name, last_name) values ('Mikko', 'Pasanen')
insert into minister(first_name, last_name) values ('Jari', 'Pigg')
insert into minister(first_name, last_name) values ('Allen', 'Pirness')
insert into minister(first_name, last_name) values ('Arvin', 'Pirness')
insert into minister(first_name, last_name) values ('Martin', 'Pirness')
insert into minister(first_name, last_name) values ('Roger', 'Plough')
insert into minister(first_name, last_name) values ('Thomas', 'Prophet')
insert into minister(first_name, last_name) values ('Martin', 'Pylvainen')
insert into minister(first_name, last_name) values ('Daniel', 'Rintamaki')
insert into minister(first_name, last_name) values ('Michael', 'Riutta')
insert into minister(first_name, last_name) values ('Russell', 'Roiko')
insert into minister(first_name, last_name) values ('Samuel', 'Roiko')
insert into minister(first_name, last_name) values ('Kevin', 'Ruonavaara')
insert into minister(first_name, last_name) values ('Quentin', 'Ruonavaara')
insert into minister(first_name, last_name) values ('Terry', 'Ruonavaara')
insert into minister(first_name, last_name) values ('Travis', 'Ruonavaara')
insert into minister(first_name, last_name) values ('Raimo', 'Savolainen')
insert into minister(first_name, last_name) values ('Arthur', 'Simonson')
insert into minister(first_name, last_name) values ('Bryan', 'Simonson')
insert into minister(first_name, last_name) values ('Carey', 'Simonson')
insert into minister(first_name, last_name) values ('Curtis', 'Simonson')
insert into minister(first_name, last_name) values ('Eric', 'Simonson')
insert into minister(first_name, last_name) values ('Martin', 'Simonson')
insert into minister(first_name, last_name) values ('Richard', 'Simonson')
insert into minister(first_name, last_name) values ('Ronald', 'Simonson')
insert into minister(first_name, last_name) values ('Scott', 'Simonson')
insert into minister(first_name, last_name) values ('Mark', 'Smith')
insert into minister(first_name, last_name) values ('Rodrick', 'Sorvala')
insert into minister(first_name, last_name) values ('Rory', 'Sorvala')
insert into minister(first_name, last_name) values ('Swen', 'Sorvala')
insert into minister(first_name, last_name) values ('John', 'Stewart')
insert into minister(first_name, last_name) values ('Thomas', 'Stewart')
insert into minister(first_name, last_name) values ('William', 'Sturos')
insert into minister(first_name, last_name) values ('Olli', 'Vänskä')
insert into minister(first_name, last_name) values ('Benjamin', 'Waaraniemi')
insert into minister(first_name, last_name) values ('Keith', 'Waaraniemi')
insert into minister(first_name, last_name) values ('Neil', 'Waaraniemi')
insert into minister(first_name, last_name) values ('Ray', 'Waaraniemi')
insert into minister(first_name, last_name) values ('Jari', 'Warwaruk')
insert into minister(first_name, last_name) values ('Marvin', 'Wittenberg')
insert into minister(first_name, last_name) values ('Martin', 'Wuollet')
insert into minister(first_name, last_name) values ('Kenneth', 'Wuollet')
insert into minister(first_name, last_name) values ('Troy', 'Wuollet')
insert into minister(first_name, last_name) values ('Clayton', 'Ylioja')
insert into minister(first_name, last_name) values ('Stanley', 'Ylioja')


--- Books
insert into book(name, abbreviation, testament) values('Genesis','Gen.','Old Testament')
insert into book(name, abbreviation, testament) values('Exodus','Exo.','Old Testament')
insert into book(name, abbreviation, testament) values('Leviticus','Lev.','Old Testament')
insert into book(name, abbreviation, testament) values('Numbers','Num.','Old Testament')
insert into book(name, abbreviation, testament) values('Deuteronomy','Deut.','Old Testament')
insert into book(name, abbreviation, testament) values('Joshua','Josh.','Old Testament')
insert into book(name, abbreviation, testament) values('Judges','Judg.','Old Testament')
insert into book(name, abbreviation, testament) values('Ruth','Ruth','Old Testament')
insert into book(name, abbreviation, testament) values('1 Samuel','1 Sam.','Old Testament')
insert into book(name, abbreviation, testament) values('2 Samuel','2 Sam.','Old Testament')
insert into book(name, abbreviation, testament) values('1 Kings','1 Kgs.','Old Testament')
insert into book(name, abbreviation, testament) values('2 Kings','2 Kgs.','Old Testament')
insert into book(name, abbreviation, testament) values('1 Chronicles','1 Chron.','Old Testament')
insert into book(name, abbreviation, testament) values('2 Chronicles','2 Chron.','Old Testament')
insert into book(name, abbreviation, testament) values('Ezra','Ezra','Old Testament')
insert into book(name, abbreviation, testament) values('Nehemiah','Neh.','Old Testament')
insert into book(name, abbreviation, testament) values('Esther','Esth.','Old Testament')
insert into book(name, abbreviation, testament) values('Job','Job','Old Testament')
insert into book(name, abbreviation, testament) values('Psalms','Psa.','Old Testament')
insert into book(name, abbreviation, testament) values('Proverbs','Prov.','Old Testament')
insert into book(name, abbreviation, testament) values('Ecclesiastes','Eccl.','Old Testament')
insert into book(name, abbreviation, testament) values('Song of Solomon','S.of S.','Old Testament')
insert into book(name, abbreviation, testament) values('Isaiah','Isa.','Old Testament')
insert into book(name, abbreviation, testament) values('Jeremiah','Jer.','Old Testament')
insert into book(name, abbreviation, testament) values('Lamentations','Lam.','Old Testament')
insert into book(name, abbreviation, testament) values('Ezekiel','Eze.','Old Testament')
insert into book(name, abbreviation, testament) values('Daniel','Dan.','Old Testament')
insert into book(name, abbreviation, testament) values('Hosea','Hos.','Old Testament')
insert into book(name, abbreviation, testament) values('Joel','Joel','Old Testament')
insert into book(name, abbreviation, testament) values('Amos','Amos','Old Testament')
insert into book(name, abbreviation, testament) values('Obadiah','Obad.','Old Testament')
insert into book(name, abbreviation, testament) values('Jonah','Jon.','Old Testament')
insert into book(name, abbreviation, testament) values('Micah','Mic.','Old Testament')
insert into book(name, abbreviation, testament) values('Nahum','Nah.','Old Testament')
insert into book(name, abbreviation, testament) values('Habakkuk','Hab.','Old Testament')
insert into book(name, abbreviation, testament) values('Zephaniah','Zeph.','Old Testament')
insert into book(name, abbreviation, testament) values('Haggai','Hag.','Old Testament')
insert into book(name, abbreviation, testament) values('Zechariah','Zech.','Old Testament')
insert into book(name, abbreviation, testament) values('Malachi','Mal.','Old Testament')
insert into book(name, abbreviation, testament) values('Matthew','Matt.','New Testament')
insert into book(name, abbreviation, testament) values('Mark','Mark','New Testament')
insert into book(name, abbreviation, testament) values('Luke','Luke','New Testament')
insert into book(name, abbreviation, testament) values('John','John','New Testament')
insert into book(name, abbreviation, testament) values('Acts','Acts','New Testament')
insert into book(name, abbreviation, testament) values('Romans','Rom.','New Testament')
insert into book(name, abbreviation, testament) values('1 Corinthians','1 Cor.','New Testament')
insert into book(name, abbreviation, testament) values('2 Corinthians','2 Cor.','New Testament')
insert into book(name, abbreviation, testament) values('Galatians','Gal.','New Testament')
insert into book(name, abbreviation, testament) values('Ephesians','Eph.','New Testament')
insert into book(name, abbreviation, testament) values('Philippians','Phil.','New Testament')
insert into book(name, abbreviation, testament) values('Colossians','Col.','New Testament')
insert into book(name, abbreviation, testament) values('1 Thessalonians','1 Thes.','New Testament')
insert into book(name, abbreviation, testament) values('2 Thessalonians','2 Thes.','New Testament')
insert into book(name, abbreviation, testament) values('1 Timothy','1 Tim.','New Testament')
insert into book(name, abbreviation, testament) values('2 Timothy','2 Tim.','New Testament')
insert into book(name, abbreviation, testament) values('Titus','Tit.','New Testament')
insert into book(name, abbreviation, testament) values('Philemon','Phile.','New Testament')
insert into book(name, abbreviation, testament) values('Hebrews','Heb.','New Testament')
insert into book(name, abbreviation, testament) values('James','Jas.','New Testament')
insert into book(name, abbreviation, testament) values('1 Peter','1 Pet.','New Testament')
insert into book(name, abbreviation, testament) values('2 Peter','2 Pet.','New Testament')
insert into book(name, abbreviation, testament) values('1 John','1 John','New Testament')
insert into book(name, abbreviation, testament) values('2 John','2 John','New Testament')
insert into book(name, abbreviation, testament) values('3 John','3 John','New Testament')
insert into book(name, abbreviation, testament) values('Jude','Jude','New Testament')
insert into book(name, abbreviation, testament) values('Revelation','Rev.','New Testament')


insert into congregation(name, full_name) values('rllc', 'Rockford Laestadian Luthern Church')
insert into congregation(name, full_name) values('mllc', 'Minneapolis Laestadian Luthern Church')

insert into amazon_credentials(access_key, secret_key, bucket) values('accessKey', 'secretKey', 'bucket')
-- update congregation set amazon_credentials_id=1 where congregation_id=1

insert into sermon(congregation_id, minister_id, date, comments) values(1, 2, GETDATE(), 'Marys Day Services')
insert into bible_text(sermon_id, chapter, start, end) values(1, 2, 10, 20)

insert into sermon(congregation_id, minister_id, comments) values(1, 4, 'St Johns Services')
insert into bible_text(sermon_id, chapter, start, end) values(2, 4, 11, 12)