version: '2'
services:
  web:
    image: llc/llc-archives
    ports:
      - "9090:8080"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=llc
